### ISSUE TITLE
Create GUI for the restaurant.

### ISSUE THREAD

**Issue by Avir4m** [Nitch-dev/RestaurantsSystem#1]
Ordering Page:
- Menu
- Pricing/Total

Login/SignUp Page:
- Create Account
- Log In
- Forgot Password (nice feature to have)

Admin Panel:
- Create Items on the menu
- See Orders

**Comment by Nitch-dev** [comment]
You work on UI and while i see firebase with python

**Comment by Avir4m** [comment]
@Nitch-dev Tell if there is anythink you would like to change/add.

**Comment by Nitch-dev** [comment]
No, Great Work !

**Comment by Avir4m** [comment]
Didn't finish the code...
